// <auto-generated />
namespace ARSM___Avtobusi_R.S.Makedonija.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Ticket2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ticket2));
        
        string IMigrationMetadata.Id
        {
            get { return "202208190122237_Ticket2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
