// <auto-generated />
namespace ARSM___Avtobusi_R.S.Makedonija.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedTextRoute : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedTextRoute));
        
        string IMigrationMetadata.Id
        {
            get { return "202208191051148_addedTextRoute"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
